[servo]
# Update this path after building Servo on Linux
executable_path = "/home/user/servo/target/debug/servo"
mode = "real"

[integration]
enable_real_integration = true
use_javascript_injection = true

[debug]
verbose_logging = true
show_servo_output = true
